# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Stock Management Module Specific Rules
# Following Rails Omakase conventions for all stock-related code
# - app/models/stock*.rb
# - app/controllers/**/stock*.rb
# - app/services/*stock*.rb
# No additional overrides needed - Omakase covers our needs
